import type { Metadata } from "next";
import "./globals.css";
import { poppins, playball } from './fonts';


export const metadata: Metadata = {
  title: "Cader Rahmathulla",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${poppins.variable} ${playball.variable}`}>
      <body className="font-poppins">
       
        {children}
      </body>
    </html>
  );
}